# Generated by Django 3.2.5 on 2021-08-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_dojos_ninjas'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojos',
            name='desc',
            field=models.CharField(default='dojo antiguo', max_length=255),
        ),
    ]
